config/routes.rb
Rails.application.routes.draw do

  

  # devise_for :admins
    
  # resources :reciepts do
  # 	collection do
  #     match 'search' => 'reciepts#search', via: [:get, :post], as: :search
  #   end
  # end
 
  resources :reciepts 


  devise_for :users

  resources :users_admin, :controller => 'users'
 
 # resources :admins, except: :create

 # post 'create_user' => 'users#create', as: :create_user


  resources :reports do
      collection do
        match 'search' => 'reports#index', via: [:get, :post], as: :search
      end
    end
     
   


  root 'dashboard#index'
  # get 'dashboard/reciept'
  # get 'dashboard/invoice'

   


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reciept.rb
class Reciept < ApplicationRecord
    
    

	validates :name, presence: true
	validates :address, presence: true
	validates :contact, presence: true, numericality: true
	validates :reciever, presence: true
	validates :amount, presence: true, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :validatable
    devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 # before_action :authenticate_user!
 #    before_action :deny_to_visitors

 #    private

	# def deny_to_visitors
	#   redirect_to new_user_session_path unless user_signed_in? or admin_signed_in?
	# end
   # before_action :authenticate_admin!
   before_action :authenticate_user!
  
   

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
   # before_action :authenticate_user!
  
  def index
  	
  end

end

app/controllers/reciepts_controller.rb
class RecieptsController < ApplicationController
  
   before_action :set_reciept, only: [:show, :edit, :update, :destroy]
  
  
   
  def index
    @search = Reciept.search(params[:q])
    @reciepts = @search.result
    
    @reciepts = Reciept.all.order(id: :desc).paginate(:page => params[:page], :per_page => 5)
  end

  # def search
  #     index
  #     render :template => 'reports/index'
  # end

  def show
  end

  def new
    @reciept = Reciept.new
  end

  def edit
  end

  def create
    @reciept = Reciept.new(reciept_params)
     respond_to do |format|
      require 'uri'
      require 'net/http'
      if @reciept.save
        format.html { redirect_to @reciept, notice: 'Reciept was successfully created.' }
        format.json { render :show, status: :created, location: @reciept }
      else
        format.html { render :new }
        format.json { render json: @reciept.errors, status: :unprocessable_entity }
      end
    end

    uri = URI("http://api.msg91.com/api/sendhttp.php?sender=temple&route=4&mobiles=#{@reciept.contact}&authkey=-----------&encrypt=&message={text_message}")
          req = Net::HTTP.get(uri)
          puts req 
  end

  def update
    respond_to do |format|
      if @reciept.update(reciept_params)
        format.html { redirect_to @reciept, notice: 'Reciept was successfully updated.' }
        format.json { render :show, status: :ok, location: @reciept }
      else
        format.html { render :edit }
        format.json { render json: @reciept.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reciept.destroy
    respond_to do |format|
      format.html { redirect_to reciepts_url, notice: 'Reciept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_reciept
      @reciept = Reciept.find(params[:id])
    end


    def reciept_params
      params.require(:reciept).permit(:name, :address, :contact, :amount, :reciever, :date, :reciept_type, :payment_mode)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	def index

		if params[:search].present?
		  items = JSON.parse(params[:search].gsub('=>', ':'))
		  @search = Reciept.search(items)
		else
		  @search = Reciept.search(params[:q])
		end
		
	    @reciepts = @search.result.order(id: :desc)
	 
	    respond_to do |format|
	      format.html
	      format.json
	      format.pdf {render pdf: 'Reciepts'}
	    end
	    
	end
    

	# def search
	#     index
	#     render :index 
 #    end
# def search
#       index
#       render :template => 'reports/index'
#   end
   

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :authorize_admin

    def index
    	@users = User.where.not(id: current_user.id)


    end

    def new
    	@user = User.new
    end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to users_admin_index_path
		else
			render :new
		end
	end

	def destroy
		 User.find(params[:id]).destroy
	    
	    redirect_to users_admin_index_url
	    
    end


	def authorize_admin
		redirect_to root_path, alert: 'Access Denied' unless current_user.admin?
	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/reciepts_helper.rb
module RecieptsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<div id="page-wrapper">
  <div class="main-page">
	  <h2 class="title1">Dashboard</h2>
		      
    <div class="agil-info-calendar">
    <!-- calendar -->
    <div class="col-md-4 agile-calendar">
      <div class="calendar-widget">
                     <!--  <header class="widget-header">
                        <h4 class="widget-title">Calender</h4>
                      </header> -->
              <!-- <hr class="widget-separator"> -->
        <!-- grids -->
          <div class="agile-calendar-grid">
            <div class="page">
              
              <div class="w3l-calendar-left">
                <div class="calendar-heading">
                  
                </div>
                <div class="monthly" id="mycalendar"></div>
              </div>
              
              <div class="clearfix"> </div>
            </div>
          </div>
      </div>
    </div>
   <!--  <div class="col-md-4 stats-info widget">
            <div class="stats-info-agileits">
                                        <header class="widget-header">
                                            <h4 class="widget-title">Browser stats</h4>
                                        </header>
                                        <hr class="widget-separator">
              <div class="stats-body">
                <ul class="list-unstyled">
                  <li>GoogleChrome <span class="pull-right">85%</span>  
                    <div class="progress progress-striped active progress-right">
                      <div class="bar green" style="width:85%;"></div> 
                    </div>
                  </li>
                  <li>Firefox <span class="pull-right">35%</span>  
                    <div class="progress progress-striped active progress-right">
                      <div class="bar yellow" style="width:35%;"></div>
                    </div>
                  </li>
                  <li>Internet Explorer <span class="pull-right">78%</span>  
                    <div class="progress progress-striped active progress-right">
                      <div class="bar red" style="width:78%;"></div>
                    </div>
                  </li>
                  <li>Safari <span class="pull-right">50%</span>  
                    <div class="progress progress-striped active progress-right">
                      <div class="bar blue" style="width:50%;"></div>
                    </div>
                  </li>
                  <li>Opera <span class="pull-right">80%</span>  
                    <div class="progress progress-striped active progress-right">
                      <div class="bar light-blue" style="width:80%;"></div>
                    </div>
                  </li>
                  <li>Microsoft Edge <span class="pull-right">78%</span>  
                    <div class="progress progress-striped active progress-right">
                      <div class="bar red" style="width:78%;"></div>
                    </div>
                  </li>
                  <li class="last">Others <span class="pull-right">60%</span>  
                    <div class="progress progress-striped active progress-right">
                      <div class="bar orange" style="width:60%;"></div>
                    </div>
                  </li> 
                </ul>
              </div>
            </div>
          </div> -->
          <div class="col-md-4 chart-layer1-right"> 
            <div class="user-marorm">
            <div class="malorum-top">       
            </div>
            <div class="malorm-bottom">
              <span class="malorum-pro"> </span>
               <!-- <h2>Calorine ELiza</h2>
              <p>Fusce elit sem, dictum non gravida vitae, pulv
              inar ac mi. Proin aliquet ex nunc, sodales efficitur 
              ris imperdiet et. Vestibulum antei psum primis in faucibus orci luctus et </p> -->
              <!-- <ul class="malorum-icons">
                <li><a href="#"><i class="fa fa-facebook"> </i>
                  <div class="tooltip"><span>Facebook</span></div>
                </a></li>
                <li><a href="#"><i class="fa fa-twitter"> </i>
                  <div class="tooltip"><span>Twitter</span></div>
                </a></li>
                <li><a href="#"><i class="fa fa-google-plus"> </i>
                  <div class="tooltip"><span>Google</span></div>
                </a></li>
              </ul> -->
            </div>
             </div>
          </div>
    <div class="clearfix"></div>
    </div>
    <!-- //calendar --> 
  </div>
</div>
 
 

app/views/layouts/_footer.html.erb
 
    <div class="footer">
	   <p>&copy; 2018 Chintamani Temple Kalamb.</p>
	</div>
 
 
 
 

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
<div class="main-content">

	<div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left"    id="cbp-spmenu-s1">
	 <aside class="sidebar-left">
      <nav class="navbar navbar-inverse">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <h1><a class="navbar-brand" href="#">
            	<!-- <span class="fas fa-om" style="font-size:50px;color:orange"></span> -->&nbsp; &nbsp; &nbsp; &nbsp;<span class="fas fa-yin-yang" style="font-size:50px;color:orange"></span> <br/><br/>Chintamani<span class="dashboard_text">Temple ERP</span></a></h1>
          </div>
          <br/>
          <br/>
          <br/>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="sidebar-menu">
              <!-- <li class="header">MAIN NAVIGATION</li> -->
              <li class="treeview">
                <%= link_to root_path do %>
                  <i class="fas fa-tachometer-alt"></i> Dashboard
                <% end %>
                   
              </li>

              <li class="treeview">
                <%= link_to new_reciept_path do %>
                  <i class="fas fa-print"></i> Reciept
                <% end %>
                   
              </li>
			 
      
            <% if current_user.admin? %> 

              <li class="treeview">
                <a href="#">
                <i class="fas fa-wallet"></i> <span>Salary</span>
                </a>
              </li>


              <li class="treeview">
                <a href="#">
                <i class="fas fa-rupee"></i> <span>Expenditure</span>
                </a>
              </li>

            <li class="treeview">
                <a href="#">
                <i class="fas fa-file"></i>
                <span>Reports</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  
                  <li>
                    <%= link_to reports_path do %>
                      <i class="fa fa-angle-right"></i>Reciepts Reports
                    <% end %>
                  </li>
                
                 </ul>
              </li>
           
              <li class="treeview">
                <a href="#">
                <i class="fas fa-user-cog"></i>
                <span>Users</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  
                  <li>
                    <%= link_to new_users_admin_path do %>
                      <i class="fa fa-angle-right"></i>Add New User
                    <% end %>
                  </li>
                  <li>
                    <%= link_to users_admin_index_path do %>
                      <i class="fa fa-angle-right"></i>Show All Users
                    <% end %>
                  </li>
               
                 </ul>
              </li>
            <% end %>
            </ul>
          </div>
        
      </nav>
     </aside>
	</div>
		 
	<div class="sticky-header header-section ">
		<div class="header-left">
				
				<button id="showLeftPush"><i class="fa fa-bars"></i></button>
			
				 
				<div class="clearfix"> </div>
		</div>
	<div class="header-right">
				
	
	    <div class="profile_details">		
					<ul>
						<li class="dropdown profile_details_drop">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
								<div class="profile_img">	
									<span class="prfil-img"><img src="/assets/avatar.png" alt=""> </span> 
									<div class="user-name">
                     <% if current_user.admin? %> 
										<p>Admin</p>
                    <% else %>
                    <p>User</p>
                    <% end %>
										<span>Administrator</span>
									</div>
									<i class="fa fa-angle-down lnr"></i>
									<i class="fa fa-angle-up lnr"></i>
									<div class="clearfix"></div>	
								</div>	
							</a>
							<ul class="dropdown-menu drp-mnu">
								

								<li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                   <i class="fa fa-user"></i>Logout
                  <% end %>
                </li>


							</ul>
						</li>
					</ul>
	    </div>
	      <div class="clearfix"> </div>				
	</div>
	    <div class="clearfix"> </div>	
</div>
		 
<% end %>

app/views/reciepts/_form.html.erb
<div id="page-wrapper">
  <div class="main-page">
    <div class="forms">
      <div class="col-xs-12">

        <h5> <%= link_to 'Click Show All Reciepts', reciepts_path, class: 'btn btn-info btn-sm' %> </h5>
      <%= simple_form_for(@reciept) do |f| %>
        <div id="invoice-wrap">
          <div class="row">
          </div>
          <div class="row invoice-info">
            <form class="form-horizontal">
              <div class="col-xs-12 invoice-col">
                <label>Name</label>
                
                <%= f.text_field :name, class: "form-control", palceholder: "Name", required:"" %>
                <br/>
                <label>Address</label>
               
                <%= f.text_area :address, class: "form-control", palceholder: "Address", required:"" %>
                <br/>
                <label>Contact</label>
               
                <%= f.text_field :contact, class: "form-control", palceholder: "Contact", required:"" %>
                <br/>
                <label>Date</label>
                
                <%= f.date_select :date, class: "form-control", palceholder: "Date" %>
                <br/>
                <br/>

                
                 <label>Reciept Type</label>
                 
                   <%= f.select :reciept_type, options_for_select([['Donation'],['Abhishek'],['Bhaktinivas']]) %>
                <br/>
                <br/>
                  

                <label>Payment Mode</label>
                
                <%= f.select :payment_mode, options_for_select([['Cash'],['Swipe'],['Chaque']]) %>
 
                <br/>
                <br/>


                <label>Reciever</label>
                 
                <%= f.text_field :reciever, class: "form-control", palceholder: "Reciever Name", required:"" %>

                <br/>

                <label>Amount</label>
                <%= f.text_field :amount, class: "form-control", palceholder: "Amount", required:"" %>

                <br/>

              </div>
            </form>
            <br/>
            <div class="row">
              <div class="col-xs-12 pull-left">
                
                <%= f.button :submit, 'Submit Payment', class: 'btn btn-info btn-sm', id: "submit_invoice", data: {toggle: "modal", target: "#invoice_modal"}, :remote => true %>    
              </div>
            </div>  
            <div id="terms">
              <h5>Terms</h5>
              <textarea id="10">Write your own terms and condition statements as per requirement</textarea>
            </div>
        </div> 
      <% end %> 
      </div>
    </div>
  </div>
</div>
 
 

app/views/reciepts/edit.html.erb
<h1>Editing Reciept</h1>

<%= render 'form', reciept: @reciept %>

<%= link_to 'Show', @reciept %> |
<%= link_to 'Back', reciepts_path %>

app/views/reciepts/index.html.erb
<div id="page-wrapper">
  <div class="main-page">
    <div class="tables">
      <div class="bs-example widget-shadow" data-example-id="bordered-table">

        <p id="notice"><%= notice %></p>

       <div class="table-responsive">

        <div class="col-md-2">
          <h4>RECIEPTS</h4>
        </div>

        <div class="col-md-2">
          <%= link_to 'New Reciept', new_reciept_path, class: 'btn btn-info btn-sm' %>
        </div>


        <table class="table table-bordered">
          <thead style="background-color: #f2b33f;">
            <tr>
              <th>Reciept_No.</th>
              <th>Name</th> 
              <th>Address</th> 
              <th>Contact No.</th> 
              <th>Date</th> 
              <th>Reciept Type</th> 
              <th>Payment Mode</th>
              <th>Receiver</th>
              <th>Amount</th>
              <th>Action</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @reciepts.each do |reciept| %>
           
              <tr>
                <td><%= reciept.id %></td>
                <td><%= reciept.name %></td>
                <td><%= reciept.address %></td>
                <td><%= reciept.contact %></td>
                <td><%= reciept.date %></td>
                <td><%= reciept.reciept_type %></td>
                <td><%= reciept.payment_mode %></td>
                <td><%= reciept.reciever %></td>
                <td><%= reciept.amount %></td>
                <td><%= link_to 'Show', reciept, class: 'btn btn-success btn-sm' %></td>
                <td><%= link_to 'Edit', edit_reciept_path(reciept), class: 'btn btn-success btn-sm' %></td>
                <td><%= link_to 'Destroy', reciept, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-success btn-sm' %></td>
                
              </tr>
              
            <% end %>
          </tbody>

        </table>
      </div>
      <div id='will_paginate_id'>
         <%= will_paginate @reciepts%>
      </div>
        <br>

        <%= link_to 'New Reciept', new_reciept_path, class: 'btn btn-info btn-sm' %>


       </div>
    </div>
  </div>
</div>

app/views/reciepts/new.html.erb
<%= render 'form', reciept: @reciept %>

<%= link_to 'Back', reciepts_path %>

app/views/reciepts/show.html.erb
<div id="page-wrapper">
  <div class="main-page">
    <div class="row">
       <div class="form-three widget-shadow">

           <table class="table table-bordered">

			<p id="notice"><%= notice %></p>
			  <br/>
              <tr>
			      <td>  <strong>Reciept No.:</strong></td>
			      <td>  <%= @reciept.id %></td>
		      </tr>

		      <tr>
			      <td>  <strong>Name:</strong></td>
			      <td> <%= @reciept.name %></td>
		      </tr>

		      <tr>
			      <td><strong>Address:</strong></td>
			      <td> <%= @reciept.address %></td>
		      </tr> 
              
              <tr>
			      <td> <strong>Contact:</strong></td>
			      <td> <%= @reciept.contact %></td>
		      </tr>

		      <tr>
			      <td> <strong>Date:</strong></td>
			      <td>  <%= @reciept.date %></td>
		      </tr>
		      
		      <tr>
			      <td>  <strong>Reciept Type:</strong></td>
			      <td>  <%= @reciept.reciept_type %></td>
		      </tr>
		      
		      <tr>
			      <td>  <strong>Payment Mode:</strong></td>
			      <td>  <%= @reciept.payment_mode %></td>
		      </tr>

		      <tr>
			      <td>  <strong>Reciever:</strong></td>
			      <td>  <%= @reciept.reciever %></td>
		      </tr>

		      <tr>
			      <td>  <strong>Amount:</strong></td>
			      <td>  <%= @reciept.amount %></td>
		      </tr>
		      
		  </table>
            <a class="btn btn-info btn-sm" id="invoice_button" data-toggle="modal" data-target="#invoice_modal">Print Reciept</a>|
			<%= link_to 'Edit', edit_reciept_path(@reciept) %> |
			<%= link_to 'Back', reciepts_path %>

       </div>
    </div>
  </div>
</div>



<div class="modal fade" id="invoice_modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" style="width:920px;" >
    
      <div class="container-fluid invoice_wrapper"  id="print-me" style="margin:10px; ">
       <div class="main-page" style="border: 1px; border-color: #0000;">
<div class="row">

  <div class="col-xs-12" style="border-bottom: thick double #ff0000;">
    <div class="col-md-12">
              <img src="/assets/logo.jpg" style="height: 70px; width: 80px; padding-right: 0;">
              <img src="/assets/banner.jpg" style="height: 70px; width: 400px; padding-right: 0;">
            </div>
   </div>

</div>

<div class="row">
  <div class="panel-body widget-shadow">
    <h4>Thanks For Your Valuable Donation!!!!</h4>
    <br/>
     <table class="table table-bordered"> 
      <thead> 
       
      </thead> 
      
      <tbody > 
        <tr>
          <td>
            <label>Reciept No.</label>
          </td>
          <td>
            <%= @reciept.id %>
          </td>
        </tr>
        <tr>
          <td>
            <label>Name</label>
          </td>
          <td>
            <%= @reciept.name %>
          </td>
        </tr>

        <tr>
          <td>
            <label>Address</label>
          </td>
          <td>
            <%= @reciept.address %>
          </td>
        </tr>

        <tr>
          <td>
            <label>Contact</label>
          </td>
          <td>
            <%= @reciept.contact %>
          </td>
        </tr>

        <tr>
          <td>
            <label>Date</label>
          </td>
          <td>
            <%= @reciept.date %>
          </td>
        </tr>

        <tr>
          <td>
            <label>Reciept Type</label>
          </td>
          <td>
            <%= @reciept.reciept_type %>
          </td>
        </tr>

        <tr>
          <td>
            <label>Payment Mode</label>
          </td>
          <td>
            <%= @reciept.payment_mode %>
          </td>
        </tr>

        <tr>
          <td>
            <label>Reciever</label>
          </td>
          <td>
            <%= @reciept.reciever %>
          </td>
        </tr>

        <tr>
          <td>
            <label>Amount</label>
          </td>
          <td>
            <%= @reciept.amount %>
          </td>
        </tr>
          
          
      </tbody> 
    </table>
  </div>
</div>
 
<div>
  
  <!-- <span>Please Note: THIS IS NOT AN OFFICIAL RECEIPT, THIS IS ONLY PAYMENT ADVICE</span> -->
</div>

</div> 
      </div>
     
      <div class="modal-footer">
      <button class="btn btn-primary" onclick="printDiv('print-me')">Print & Save</button>
      </div>  
    </div>
  </div>
</div>
  

app/views/reports/index.html.erb
<div id="page-wrapper">
  <div class="main-page">
    <h2 class="title1">Receipts Reports</h2>
    <div class="tables">
      <div class="bs-example widget-shadow" data-example-id="bordered-table">

        <p id="notice"><%= notice %></p>

       <div class="table-responsive">

           
           <%= search_form_for @search, url: search_reports_path, html: {class: "form-inline col-md-12", method: :post} do|f| %>
             <!-- <div class="input-daterange"> -->

                <div class="col-md-5">
                 <lable>From</lable>
                  <%= f.date_field :date_gteq, placeholder: "From", class: "form-control" %>
                </div> 
                
                <div class="col-md-5">
                  <lable>To</lable>
                  <%= f.date_field :date_lteq, placeholder: "To", class: "form-control" %>
                </div>

                <!-- </div> -->
                <div class="col-md-2 form-actions">
                  <%= f.submit "Search", class: "btn btn-success" %>
                </div>
              
            <% end %>
        
  

        <table class="table table-striped table-bordered" style="margin-top: 60px;">
          <thead style="background-color: #f2b33f;">
            <tr>
              <th>Reciept_No.</th>
              <th>Name</th> 
              <th>Address</th> 
              <th>Contact No.</th> 
              <th>Date</th> 
              <th>Reciept Type</th> 
              <th>Payment Mode</th>
              <th>Receiver</th>
              <th>Amount</th>
            </tr>
          </thead>

          <tbody>
            <% @reciepts.each do |reciept| %>
           
              <tr>
                <td><%= reciept.id %></td>
                <td><%= reciept.name %></td>
                <td><%= reciept.address %></td>
                <td><%= reciept.contact %></td>
                <td><%= reciept.date %></td>
                <td><%= reciept.reciept_type %></td>
                <td><%= reciept.payment_mode %></td>
                <td><%= reciept.reciever %></td>
                <td><%= reciept.amount %></td>
                </tr>
              
            <% end %>
          </tbody>

         </table>
        </div>
        
      
       <%= link_to "Download PDF File", reports_path(@reciepts, format: 'pdf',search: "#{params[:q]}")%>
       </div>

    </div>
  </div>
</div>

app/views/reports/index.pdf.erb
<h2 class="title1">Receipts Reports</h2>
<div class="tables">
  <div class="bs-example widget-shadow" data-example-id="bordered-table">
    <table class="table table-bordered">
          <thead>
            <tr>
              <th>Reciept_No.</th>
              <th>Name</th> 
              
              <th>Contact No.</th> 
              <th>Date</th> 
              <th>Reciept Type</th> 
              <th>Payment Mode</th>
              <th>Receiver</th>
              <th>Amount</th>
            </tr>
          </thead>
    
          <tbody>
            <% @reciepts.each do |reciept| %>
           
              <tr>
                <td><%= reciept.id %></td>
                <td><%= reciept.name %></td>
                
                <td><%= reciept.contact %></td>
                <td><%= reciept.date %></td>
                <td><%= reciept.reciept_type %></td>
                <td><%= reciept.payment_mode %></td>
                <td><%= reciept.reciever %></td>
                <td><%= reciept.amount %></td>
                </tr>
            <% end %>
          </tbody>
    </table>
  </div>
</div>


<style type="text/css">


 td,  th {
  border: 1px solid #ddd;
  padding: 8px;
}

 tr:nth-child(even){background-color: #f2f2f2;}

 tr:hover {background-color: #ddd;}

 th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #f2b33f;
  color: white;
}
</style>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div id="page-wrapper">
  <div class="main-page">
    <div class="tables">
      <div class="bs-example widget-shadow" data-example-id="bordered-table"> 
        <%= link_to 'Add New User', new_users_admin_path, :class=> "btn btn-info btn-flat btn-pri btn-sm" %>
        <br/>
        <br/>
        <h4>All Users</h4>
        <table class="table table-bordered"> 
          <thead> 
            <tr> 
              <th>Email</th> 
              
              <th>Action</th> 
            </tr> 
          </thead> 
          <tbody> 
            <% @users.each do |user| %>
              <tr>
                <td><%= user.email %></td>
               
                <td>  
                <%= link_to 'Destroy', users_admin_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-success btn-sm' %>       
                  
                </td>  
              </tr>
            <% end %> 
          </tbody> 
        </table>
      </div>
    </div>
  </div>
</div>
 

app/views/users/new.html.erb
<div id="page-wrapper">
 <div class="main-page signup-page">
        <h2 class="title1">Create User</h2>
        <div class="sign-up-row widget-shadow">


<%= form_for @user, url:users_admin_index_path(@user) do |f| %>
    <div class="sign-u">
                
                <%= f.email_field :email, placeholder:"Email Address", required:""%>
            <div class="clearfix"> </div>
          </div>
          
          
          <div class="sign-u">
                
                <%= f.password_field :password,placeholder:"Password", required:"" %>
            <div class="clearfix"> </div>
          </div>
          <div class="sign-u">
                
                <%= f.password_field :password_confirmation, placeholder:"Confirm Password", required: "" %>
            </div>
            <div class="clearfix"> </div>
          <div class="sub_home">
            
              <%= f.submit "Sign up" %>
            <div class="clearfix"> </div>
          </div>
<% end %>

</div>
</div>
</div>